= Rancher

The Oxide Rancher node driver lets Rancher provision Oxide instances and use
them to launch and manage Kubernetes clusters. This configuration creates
an RKE2 cluster running on SUSE Linux Micro instances, installs Rancher into
the RKE2 cluster, configures the Oxide Rancher node driver, and provisions a
Kubernetes cluster on Oxide using the node driver.

== Requirements

To follow this guide you'll need the following.

* Oxide API credentials for your silo. Refer to
link:/cli/guides/introduction#_authentication[Authentication] for instructions
on generating API credentials.

* An IP pool linked to your Oxide silo. This is used to access Rancher RKE2
nodes via SSH and to access the Kubernetes API.

* A SUSE Customer Center (SCC) registration code and email address entitled to
SUSE Linux Micro.

* `qemu-img`: Used to convert the base SUSE Linux Micro image from QCOW2 to raw.

* link:https://developer.hashicorp.com/packer[Packer]: Used to build the SUSE
Linux Micro image.

* link:https://developer.hashicorp.com/terraform[Terraform]: Used to deploy
Rancher RKE2, the node driver, and create the Kubernetes cluster.

* `kubectl`: Used to connect to the created Kubernetes cluster.

== Architecture

This guide deploys a 3-node Rancher RKE2 cluster in the following layout.

* `rke-01`: Initial cluster node. A floating IP is attached to this node for
Kubernetes API access. All other nodes join this node to form a cluster.
* `rke-02`: Generic RKE2 node.
* `rke-03`: Generic RKE2 node.

The node driver is installed into this cluster and used to launch a Kubernetes
cluster on Oxide running the following layout.

* 3 control plane nodes
* 3 worker nodes

Longhorn is then installed in the Kubernetes cluster and a Kubernetes workload
started that uses a Longhorn volume.

== Usage

The configuration is split across the following subdirectories, meant to be run
in the following order.

. link:./image[`image`]: Builds the SUSE Linux Micro image used for RKE2 and Kubernetes.
. link:./rke2[`rke2`]: Creates an RKE2 cluster running on SUSE Linux Micro instances.
. link:./rancher[`rancher`]: Installs Rancher into the RKE2 cluster.
. link:./nodedriver[`nodedriver`]: Configures the Oxide Rancher node driver within Rancher.
. link:./k8s[`k8s`]: Provisions a Kubernetes cluster on Oxide using the Rancher node driver.
. link:./longhorn[`longhorn`]: Installs Longhorn on the Kubernetes cluster and runs an `fio` benchmark.

=== Accessing Kubernetes

Once the configuration from the subdirectories is applied, you can configure
`kubectl` access to the Kubernetes cluster.

. Configure `KUBECONFIG`.
+
[source,shell]
----
export KUBECONFIG='./k8s/.kube/config'
----

== Additional Resources

* https://github.com/oxidecomputer/rancher-machine-driver-oxide[Oxide Rancher Node Driver - Source Code]
* https://rfd.shared.oxide.computer/rfd/0493[RFD 0493: Initial Kubernetes Integrations]
